site :opscode
cookbook "yum", "~> 3.0", git: "https://github.com/opscode-cookbooks/yum.git"
cookbook "yum-epel", git: "https://github.com/opscode-cookbooks/yum-epel.git"
cookbook "yum-remi", git: "git@github.com:tektoh/yum-remi.git"
cookbook "selinux"
cookbook "iptables"
cookbook "git"
cookbook "php"
cookbook "php-extends", path: "./site-cookbooks/php-extends"
cookbook "mysql"
cookbook "apache2"
cookbook "memcached"
cookbook "nodejs"
cookbook "phpmyadmin"
cookbook "phpmyadmin-alias", path: "./site-cookbooks/phpmyadmin-alias"
cookbook "i18n", git: "https://github.com/tektoh/centos-i18n.git"
cookbook "devtools", git: "https://github.com/tektoh/centos-devtools.git"
