site :opscode
cookbook "yum"
cookbook "selinux"
cookbook "iptables"
cookbook "git"
cookbook "php"
cookbook "mysql"
cookbook "apache2"
cookbook "memcached"
cookbook "composer"
cookbook "nodejs"
cookbook "phpmyadmin"
cookbook "i18n", git: "https://github.com/tektoh/centos-i18n.git"
cookbook "devtools", git: "https://github.com/tektoh/centos-devtools.git"
cookbook "webserver", path: "site-cookbooks/webserver"
